### ISSUE TITLE
Encoder input is not a tensor

### ISSUE THREAD

**Issue by numancelik34** [ambekarsameer96/GLSS#1]
Hi,

Thanks for the repo. 
I am getting the following error in line 900 (z , z_edge = encoder([next_x_images])):
ValueError: Layer encoder was called with an input that isn't a symbolic tensor. Received type: <class 'numpy.ndarray'>

**Comment by ambekarsameer96** [comment]
Hi, 
it looks like there is an issue with your data loader. Maybe the input wasn't a tensor rather np array

**Comment by numancelik34** [comment]
OK thanks.. sorted this out!

**Comment by numancelik34** [comment]
@ambekarsameer96 -> I cannot find the weights for DeepLab training in the repo: ('../../Retrain/models/Deeplabs_oPredLSPredfl075.h5')??

Thanks

**Comment by ambekarsameer96** [comment]
Hi, @numancelik34 Please change it to your trained weights path.

**Comment by scwuchung** [comment]
@ambekarsameer96  can you tell me where is this weight file ?
 ./models/vae_u-efficientnet/1/**vae-u-efficientnet_u_unfrez_128_NIR_eval.h5**
after training ,
i only have   **u-efficientnet_bce_meaniou_dice_oCompq_128_with_20p_NIR.h5**
and  vae-u-efficientnet_u_unfrez_128_NIR_latent_search_.h5.
