### ISSUE TITLE
the dataset

### ISSUE THREAD

**Issue by scwuchung** [ambekarsameer96/GLSS#4]
hi,can you tell me how to get the compaq dataset? thanks !

**Comment by ambekarsameer96** [comment]
Hi, 
You can email the author (Mike Jones) at [mjones@merl.com].

**Comment by scwuchung** [comment]
thanks

**Comment by scwuchung** [comment]
hi , it has been few days since i filled the form , but i haven't receive the SNV dataset and Hand Gesture dataset is there any other way to get the dataset?

**Comment by ambekarsameer96** [comment]
Hi,
You can renter your details in the form, it should work now. On submitting the link will be visible as a confirmation message at the form page itself. 

Best.

**Comment by scwuchung** [comment]
thank you so much ,it's very kind of you.
